- name: Ofuscar arquivos
        run: |
          npm install -g javascript-obfuscator
          # Ofusca o diretório atual e joga o resultado na pasta 'public_html'
          javascript-obfuscator ./ --output ./public_html --compact true

      - name: Deploy para Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          # O SEGREDO ESTÁ AQUI: Apontar para a pasta que criamos acima
          command: pages deploy ./public_html --project-name=scout-21
